apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-testdata-client
  namespace: q2
  labels:
    team: teampensjon
spec:
  image: repo.adeo.no:5443/navikt/pensjon-testdata-client:IMAGE_VERSION
  port: 80
  ingresses:
    - https://ptb-q2.nais.preprod.local
  replicas:
    min: 1
    max: 1
  liveness:
    path: isAlive
    port: 80
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    port: 80
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  prometheus:
    enabled: true
  env:
    - name: "SERVER_HOSTNAME"
      value: "https://pensjon-testdata-server-q2.nais.preprod.local"
