version: '3.7'
services:
  pensjon-testdata-server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - sts_endpoint_url=https://security-token-service.nais.preprod.local
      - popp_endpoint_url=https://wasapp-q2.adeo.no/popp-ws/api/inntekt
    volumes:
      - "${PWD}/server/secrets:/secrets"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - frontend

  pensjon-testdata-client:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      - SERVER_HOSTNAME=http://pensjon-testdata-server:8080
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - pensjon-testdata-server
    networks:
      - frontend

  pensjon-testdata-dolly-facade:
    build:
      context: dolly-facade
      dockerfile: Dockerfile
    ports:
      - "8081:81"
    restart: always
    depends_on:
      - pensjon-testdata-server
    networks:
      - dolly-facade

networks:
  backend:
  frontend:
  dolly-facade:
