version: '3.7'
services:
  pensjon-testdata-server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      SECRET_BASEDIR: "/"
      sts_endpoint_url: "https://security-token-service-t4.nais.preprod.local"
      popp_endpoint_url: "https://wasapp-t4.adeo.no/popp-ws/api/inntekt"
      pen_vedtaksbrev_endpoint: "https://pen:8080/pensjon-ws/Vedtaksbrev"
      pen_auto_omregning_endpoint: "https://pen:8080/pensjon-ws/BehandleAutomatiskOmregning_v1"
      norg_endpoint_url: "https://app-t1.adeo.no/norg2/api"
      preg_rest_veiet_grunnbelop_endpoint_url: "http://preg:8070/preg-ws/api/grunnbelop/veiet"
    volumes:
      - "${PWD}/server/secrets:/secrets"
    ports:
      - "8081:8080"

  pensjon-testdata-client:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      - SERVER_HOSTNAME=http://pensjon-testdata-server:8080
    ports:
      - "9090:80"
    depends_on:
      - pensjon-testdata-server

networks:
  default:
    external:
      name: pensjon-local
