# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'
services:

  testdata-server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - "${PWD}/server/secrets:/secrets"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - frontend

  testdata-client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:9090/api
        
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - testdata-server
    networks:
      - frontend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
