version: '3.7'
services:

  testdata-server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - "${PWD}/server/secrets:/secrets"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - frontend

  testdata-client:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      - SERVER_HOSTNAME=http://pensjon-testdata-server:8080
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - testdata-server
    networks:
      - frontend

networks:
  backend:
  frontend:
