apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-testdata-facade
  namespace: default
  labels:
    team: pensjontestdata
spec:
  image: {{ image }}
  port: 8081
  ingresses:
    - https://pensjon-testdata-facade.nais.preprod.local
    - https://pensjon-testdata-facade.dev.adeo.no
  liveness:
    path: isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: true
    path: prometheus
