DELETE FROM PEN.T_BRUKERREG_TJ_PEN
DELETE FROM PEN.T_UTLPERIODE_FOR_SIMULERING
DELETE FROM PEN.T_SIMULERING_2011
DELETE FROM PEN.T_I_BARNETRYGD
DELETE FROM PEN.T_BPEN075_ARBTAB_1 b
DELETE FROM PEN.T_BPEN054_ARBTAB b
DELETE FROM PEN.T_BPEN005_ARB_TAB b
DELETE FROM PEN.T_BPEN005_GS_BRV b
DELETE FROM PEN.T_BPEN005_GS_BRV b
DELETE FROM PEN.T_BPEN075_ARBTAB_2 b
DELETE FROM PEN.T_BPEN021_ARBTAB b
DELETE FROM PEN.T_BPEN035_ARBTAB b
DELETE FROM PEN.T_BPEN031_OPPTJN b
DELETE FROM PEN.T_BPEN075_LOPENDE_VEDTAK b
DELETE FROM PEN.T_BPEN020_ARBTAB b
DELETE FROM PEN.T_LIGNET_INNTEKT i
DELETE FROM PEN.T_BPEN005_GS_YT2 b
DELETE FROM PEN.T_BPEN005_GS_YT1 b
DELETE FROM PEN.T_BPEN058_ARB_TAB b
DELETE FROM PEN.T_AFP_ETTEROPP a
DELETE FROM PEN.T_BPEN068_FEILMELDING b
DELETE FROM PEN.T_AFP_ETTER_SPK a
DELETE FROM PEN.T_IVERKS_KONV i
DELETE FROM PEN.T_IVERKS_KONV i
DELETE FROM PEN.T_OS_OPPDRLINJE_S os
DELETE FROM PEN.T_BPEN039_ARBTAB
DELETE FROM PEN.T_GOMR_PATCH_ARB_T
DELETE FROM PEN.T_BATCH_PERSON_FILTER
DELETE FROM PEN.T_BPEN058_PERSONID
DELETE FROM PEN.T_INNTEKT_TPEN750
DELETE FROM PEN.T_BPEN093_OPPGAVE
DELETE FROM PEN.T_BPEN093_VEDTAK
DELETE FROM PEN.T_BPEN093_ARB_TAB
DELETE FROM PEN.T_BPEN093_INPUT
DELETE FROM PEN.T_BPEN093_SAK
DELETE FROM PEN.T_BPEN096_ARB_TAB
DELETE FROM PEN.T_VURDERT_SIVILST a
DELETE FROM PEN.T_VURDERT_SIVILST a
DELETE FROM PEN.T_SKJEMA_BARN a
DELETE FROM PEN.T_SKJEMA_RELASJON a
DELETE FROM PEN.T_BREVBESTILLING a
DELETE FROM PEN.T_VILKAR v
DELETE FROM PEN.T_OMSORG_GRUNNLAG og
DELETE FROM PEN.T_OMSORG_GRUNNLAG og
DELETE FROM PEN.T_I_GODSKRIV a
delete from PEN.T_I_SAERF_PERSON a
DELETE FROM PEN.T_BPEN056_GS_TAB a
DELETE FROM PEN.T_BPEN056_GS_TAB a
DELETE FROM PEN.T_PERS_TIL_AVST a
DELETE FROM PEN.T_PERS_TIL_GOMR a
DELETE FROM PEN.T_LEVEATTEST_HIST a
DELETE FROM PEN.T_PENSJONSORDNING a
DELETE FROM PEN.T_BPEN055_ARB_TAB a
DELETE FROM PEN.T_BPEN055_ARB_TAB a
DELETE FROM PEN.T_FORST_VIRK_DATO a
DELETE FROM PEN.T_FORST_VIRK_DATO a
DELETE FROM PEN.T_I_DIST_LA a
DELETE FROM PEN.T_GODSKRIVES a
DELETE FROM PEN.T_GODSKRIVES a
DELETE FROM PEN.T_INNTEKTSKONTROLL a
DELETE FROM PEN.T_SKJEMA a
DELETE FROM PEN.T_KRAV_ARSAK a
DELETE FROM PEN.T_I_INNT_KONT_BR a
DELETE FROM PEN.T_AFP_ETTER_FOLGE a
DELETE FROM PEN.T_I_SAERF_VEDTAK a
DELETE FROM PEN.T_SAK_AUTOBEH a
DELETE FROM PEN.T_BPEN018_ARB_TAB a
DELETE FROM PEN.T_BPEN013_ARB_TAB a
DELETE FROM PEN.T_BPEN015_OPPTJENINGSAR a
DELETE FROM PEN.T_BPEN015_ARB_TAB a
DELETE FROM PEN.T_BPEN056_ARBTAB a
DELETE FROM PEN.T_FNR_ENDRING_HIST a
DELETE FROM PEN.T_SOSKEN_DET a
DELETE FROM PEN.T_BARN_DET a
DELETE FROM PEN.T_PERSON_DET pd
DELETE FROM PEN.T_BEREGNING_VILKAR a
DELETE FROM PEN.T_TELEFON a
DELETE FROM PEN.T_SKJEMA_PERS_OPPL a
DELETE FROM PEN.T_JOURNALPOST_UTL a
DELETE FROM PEN.T_BPEN029_SAK_ARBTAB a
DELETE FROM PEN.T_SAK_TILGANG a
delete from PEN.T_AFP_OFF_GRNL a
delete from PEN.T_AFP_OFF_GRNL a
delete from PEN.T_AFP_OFF_GRNL a
DELETE FROM PEN.T_AFPEO_UTB_PER a
DELETE FROM PEN.T_UTTAKSGRAD a
DELETE FROM PEN.T_UTTAKSGRAD a
DELETE FROM PEN.T_BPEN029_OPPG_ARBTAB a
DELETE FROM PEN.T_I_OPPGAVE a
DELETE FROM PEN.T_HENDELSE a
DELETE FROM PEN.T_SIMULERT_UTB_PR a
DELETE FROM PEN.T_BPEN068_ARB_TAB a
DELETE FROM PEN.T_KONTROLLPUNKT a
DELETE FROM PEN.T_BPEN052_PERSON a
DELETE FROM PEN.T_BPEN052_PERSON a
DELETE FROM PEN.T_BPEN052_SAK a
DELETE FROM PEN.T_BPEN052_ARB_PERS a
DELETE FROM PEN.T_BPEN052_ARB_PERS a
DELETE FROM PEN.T_BPEN052_ARB_VEDT a
DELETE FROM PEN.T_BPEN052_ARB_SAK a
DELETE FROM PEN.T_UFORE_PERIODE a
DELETE FROM PEN.T_BPEN029_ARB_TAB a
DELETE FROM PEN.T_OS_KVITTERING a
DELETE FROM PEN.T_AFPEO a
DELETE FROM PEN.T_BPEN077_SAMHANDLER a
DELETE FROM PEN.T_BPEN025_HISTORY a
DELETE FROM PEN.T_AUTOBREV a
DELETE FROM PEN.T_AUTOBREV a
DELETE FROM PEN.T_VEDTAK_BERP_REL a
DELETE FROM PEN.T_VEDOMR_KRAV_MAP a
DELETE FROM PEN.T_VEDTAK_TIL_OMR a
DELETE FROM PEN.T_TILBAKEK_PR_MND a
DELETE FROM PEN.T_TILBAKEK_PR_AR a
DELETE FROM PEN.T_TILBAKEK_TOTAL a
DELETE FROM PEN.T_TAP_BER_METODE a
DELETE FROM PEN.T_BEHOLDNING a
DELETE FROM PEN.T_BELOPSENDRING b
DELETE FROM PEN.T_PERIODE_ARSAK a
DELETE FROM PEN.T_INFO_PAVIRK_REL a
DELETE FROM PEN.T_KRAV_ENHET_HIST a
DELETE FROM PEN.T_KRAV_RETUR_ARSAK a
DELETE FROM PEN.T_VILKAR_UP a
DELETE FROM PEN.T_VILK_VURD_UP a
DELETE FROM PEN.T_UTENLAND_OPPH uo
DELETE FROM PEN.T_SKJEMA_AFP_PRIV a
DELETE FROM PEN.T_VENTETILLEG_GRNL a
DELETE FROM PEN.T_BEREGNING_REL br
DELETE FROM PEN.T_BEREGNING_REL br
DELETE FROM PEN.T_BEREGNING_REL br
DELETE FROM PEN.T_UTBETALINGSGRAD_UT a
DELETE FROM PEN.T_UFORE_OPPTJENING_GRUNNLAG a
DELETE FROM PEN.T_OMSRG_OVRF_GRNL a
DELETE FROM PEN.T_DAGP_GRUNNLAG a
DELETE FROM PEN.T_INNG_EKSP_GRNL a
DELETE FROM PEN.T_YRKESSKADE a
DELETE FROM PEN.T_INST_OP_FU_PE a
DELETE FROM PEN.T_ARBEIDSFORHOLDGRUNNLAG_IEU a
DELETE FROM PEN.T_TRYGDETID_GRNL a
DELETE FROM PEN.T_TRYGDETID_GRNL a
DELETE FROM PEN.T_BARNEKULL a
DELETE FROM PEN.T_TJENESTEPEN_GRNL a
DELETE FROM PEN.T_VERNEPLIKT_AR a
DELETE FROM PEN.T_AFPEO_GRUNNLAG a
DELETE FROM PEN.T_GJELDENDE_VEDTAK_EO_AR a
DELETE FROM PEN.T_BPEN092_ARB_TAB a
DELETE FROM PEN.T_UTBETALINGSGRAD_UT a
DELETE FROM PEN.T_UFORE_OPPTJENING_GRUNNLAG a
DELETE FROM PEN.T_EO_UT_HISTORIK a
DELETE FROM PEN.T_INNTEKT a
DELETE FROM PEN.T_INNTEKT a
DELETE FROM PEN.T_INNTEKT a
DELETE FROM PEN.T_ETTEROPPGJOR_DET b
DELETE FROM PEN.T_UT_ETTEROPPGJOR a
DELETE FROM PEN.T_INST_OPPH_REF a
DELETE FROM PEN.T_TRYGDEAVTALE a
DELETE FROM PEN.T_OMSRG_GODS_GRNL a
DELETE FROM PEN.T_KLAGE_ANKE_GRNL a
DELETE FROM PEN.T_KLAGE_ANKE_GRNL a
DELETE FROM PEN.T_OPPTJN_TYPE_MAP a
DELETE FROM PEN.T_OPPTJN a
DELETE FROM PEN.T_POENGAR_MANUELL a
DELETE FROM PEN.T_TRYGDEAVTAL_DET a
DELETE FROM PEN.T_FORSTEG_TJ_PER a
DELETE FROM PEN.T_FORSTEGANG_TJ a
DELETE FROM PEN.T_TRYGDETID_KONV a
DELETE FROM PEN.T_TRYGDETID_KONV a
DELETE FROM PEN.T_TT_UTL_TRGD_AVT a
DELETE FROM PEN.T_TT_UTL_TRGD_AVT a
DELETE FROM PEN.T_TRYGDETID_EOS a
DELETE FROM PEN.T_TRYGDETID_EOS a
DELETE FROM PEN.T_BEREGNET_UTB_PERIODE_UT a
DELETE FROM PEN.T_BPEN025_ARB_PERS b
DELETE FROM PEN.T_BPEN025_AVSTEMMING_DETALJ b
DELETE FROM PEN.T_OS_TRANSAKSJON o
DELETE FROM PEN.T_BPEN090_ARB_TAB b
DELETE FROM PEN.T_BPEN091_BRUKER b
DELETE FROM PEN.T_BPEN091_INNTEKT i
DELETE FROM PEN.T_UTEO_REKJORING b
delete from PEN.T_BPEN077_ARB_TAB a
delete from PEN.T_FT_DT_ARSAK a
delete from PEN.T_BT_VILKAR a
delete from PEN.T_BT_VURDERING_PERIODE a
delete from PEN.T_ENDRET_OPPTJENINGSAR a
delete from PEN.T_FRITEKST_VURDERING a
delete from PEN.T_VILKARS_VEDTAK_BEGR a
delete from PEN.T_VILKARS_VEDTAK_BEGR a
DELETE FROM PEN.T_LAAST_DATA_LOGG_ELEMENT el
delete from PEN.T_LAAST_DATA_LOGG ldl
DELETE FROM PEN.T_INNTEKT_ABONNEMENT inntekt_abonnement
DELETE FROM PEN.T_INNTEKT_ABONNEMENT inntekt_abonnement
delete from PEN.T_AFP_TPO_UP_GRUNNLAG a
DELETE FROM PEN.T_AFP_TPO_UP_GRUNNLAG a
delete from PEN.T_BREV_INFO a
delete from PEN.T_BPEN002_MELDING m
delete from PEN.T_BPEN002_BERORT_SAK b
delete from PEN.T_BPEN002_INFOBREV i
delete from PEN.T_BPEN002_OPPGAVE o
delete from PEN.T_BPEN002_YTELSE y
UPDATE PEN.T_BEREGNING_RES br SET br.BER_PERIODE_ID = NULL, br.BER_PER_REVURD_ID = NULL
UPDATE PEN.T_VEDTAK v SET v.BER_PERIODE_ID = NULL
DELETE FROM PEN.T_BER_PERIODE bp
DELETE FROM PEN.T_BER_PERIODE bp
DELETE FROM PEN.T_BER_PERIODE bp
DELETE FROM PEN.T_BER_PERIODE bp
UPDATE PEN.T_VILKARSPROV_INFO vi SET vi.VILK_PROV_INFO_2011 = NULL, vi.VILK_PROV_INFO_2025   = NULL
DELETE FROM PEN.T_VILKARSPROV_INFO vi
DELETE FROM PEN.T_VILKARSPROV_INFO vi
UPDATE PEN.T_SISTE_UFORE_BER su SET su.UFORE_EXTRA_ID = NULL
DELETE FROM PEN.T_UFORE_EXTRA ue
UPDATE PEN.T_BEREGNING b SET b.TRYGDETID_ID = NULL
DELETE FROM PEN.T_TRYGDETID t
DELETE FROM PEN.T_TRYGDETID t
DELETE FROM PEN.T_ANT_AR_MND_DAG
UPDATE PEN.T_BEREGNING b SET b.simulering_res_id = NULL
DELETE FROM PEN.T_SIMULERING_RES sr
UPDATE PEN.T_INST_OP_RE_PE inst SET inst.REF_INST_OP_RE_PE = NULL
DELETE FROM PEN.T_INST_OP_RE_PE inst
DELETE FROM PEN.T_INST_OP_RE_PE inst
UPDATE PEN.T_KRAVLINJE kl SET kl.KRAVLINJE_S_ID = NULL
DELETE FROM PEN.T_KRAVLINJE_S kls
UPDATE PEN.T_VILKAR_VEDTAK vv SET vv.kravlinje_id = NULL
DELETE FROM PEN.T_KRAVLINJE kl
DELETE FROM PEN.T_KRAVLINJE kl
UPDATE PEN.T_PERSON_GRUNNLAG pg SET pg.gen_historik_id = NULL
DELETE FROM PEN.T_GEN_HISTORIK gen
UPDATE PEN.T_YTELSE_KOMP yt SET yt.bereg_nokkel_id = NULL
DELETE FROM PEN.T_BEREG_NOKKEL bn
DELETE FROM PEN.T_BEREG_NOKKEL bn
UPDATE PEN.T_VILKAR_VEDTAK vv SET vv.BEHANDL_PERIODE_ID = NULL
DELETE FROM PEN.T_BEHANDL_PERIODE bp
DELETE FROM PEN.T_BEHANDL_PERIODE bp
UPDATE PEN.T_YTELSE_KOMP yt SET yt.beregning_id = NULL, yt.FRADRAG_YK_BEREGNING = NULL
DELETE FROM PEN.T_BEREGNING b
UPDATE PEN.T_KRAVHODE k SET k.SIST_AP_BER_2011_ID = NULL
DELETE FROM PEN.T_SIST_AP_BER_2011 sa
UPDATE PEN.T_BEREGNING_RES br SET br.UFORETRYGD_BEREGNING_ID = NULL, br.BEREGNING_AFP_PRIVAT_FK   = NULL
DELETE FROM PEN.T_BEREGNING_2011 b
UPDATE PEN.T_KONVERTERINGSGRUNNLAG_UT k SET k.ufore_grnl_id = NULL
DELETE FROM PEN.T_UFORE_GRNL ug
DELETE FROM PEN.T_BPEN091_INNTEKT i
UPDATE PEN.T_PERSON_GRUNNLAG pg SET pg.OVERGANGSINFO_UP_TIL_UT_ID = NULL
DELETE FROM PEN.T_OVERGANGSINFO_UP_TIL_UT o
DELETE FROM PEN.T_GRUNNLAG_VEDLEGG gv
DELETE FROM PEN.T_PERSON_GRUNNLAG pg
DELETE FROM PEN.T_BASISPENSJON bp
DELETE FROM PEN.T_VILKAR_VEDTAK vv
DELETE FROM PEN.T_AFP_HISTORIK ah
DELETE FROM PEN.T_SIMULERING s
UPDATE PEN.T_BEREGNING_RES br SET br.BER_RES_AP_2011_2016_ID = NULL, br.BER_RES_AP_2025_2016_ID   = NULL
DELETE FROM PEN.T_BEREGNING_RES br
UPDATE PEN.T_KRAVHODE k SET k.KONVERTERINGSGRUNNLAG_UT_ID = NULL
DELETE FROM PEN.T_KONVERTERINGSGRUNNLAG_UT kut
UPDATE PEN.T_KRAVHODE k SET k.siste_ufore_ber_id = NULL
DELETE FROM PEN.T_SISTE_UFORE_BER ub
DELETE FROM PEN.T_KONVERTERINGSGRUNNLAG kg
DELETE FROM PEN.T_YTELSE_KOMP yk
DELETE FROM PEN.T_BEREGNING_INFO bi
UPDATE PEN.T_EO_UT_HISTORIK euh set euh.FORRIGE_EO_UT_HISTORIK_ID = NULL
delete from PEN.T_EO_UT_HISTORIK euh
update PEN.T_KRAVHODE set FORRIGE_VEDTAK_TID = null
update PEN.T_VEDTAK set REL_ALDER_VEDTAK = null
update PEN.T_VEDTAK set REL_AFP_PR_VEDTAK = null
update PEN.T_VEDTAK set BASERT_PA_VEDTAK = null
delete from PEN.T_VEDTAK
delete from PEN.T_UFORE_HISTORIK
update PEN.T_KRAVHODE set KRAVHODE_ID_FOR = null
update PEN.T_KRAVHODE set FORRIGE_IVERKSATTE_KRAV = null
delete from PEN.T_KRAVHODE
delete from PEN.T_SAK
delete from PEN.T_PERSON
delete from PEN.T_POENGREKKE
delete from PEN.T_SLUTTPOENGTALL
delete from PEN.T_PEN_UNDER_UTBET
delete from PEN.T_ANVENDT_TRYGDETID
delete from PEN.T_FREMSKRIVING_DET
delete from PEN.T_LONNSVEKST_DET
delete from PEN.T_JUST_GAR_PEN_NIV
delete from PEN.T_F_MIN_PEN_NIVA
delete from PEN.T_JUSTERING_INFO
delete from PEN.T_MIN_PEN_NIVA
delete from PEN.T_VILKVEDTAK_UFORETRYGD_GRNL
delete from PEN.T_BEREGNET_UTBINFOGRUNN_UT
delete from PEN.T_OPPTJENING_UT
delete from PEN.T_EGENOPPTJN_UT
delete from PEN.T_GJT_INFORMASJON
delete from PEN.T_OVERGANGSBELOP
delete from PEN.T_JUSTERT_BELOP
delete from PEN.T_AVKORT_INFO
delete from PEN.T_SKATTEKOMP_BELOP
delete from PEN.T_BEREGNINGSGRUNNLAG
delete from PEN.T_MINSTEYTELSE
delete from PEN.T_SATS_MINSTEYTELSE
delete from PEN.T_BER_UFORE_PER
delete from PEN.T_UFORE_EXTRA_UT
