DELETE FROM PEN.T_BRUKERREG_TJ_PEN
DELETE FROM PEN.T_UTLPERIODE_FOR_SIMULERING
DELETE FROM PEN.T_SIMULERING_2011
DELETE FROM PEN.T_I_BARNETRYGD
DELETE FROM PEN.T_BPEN075_ARBTAB_1
DELETE FROM PEN.T_BPEN054_ARBTAB
DELETE FROM PEN.T_BPEN005_ARB_TAB
DELETE FROM PEN.T_BPEN005_GS_BRV
DELETE FROM PEN.T_BPEN005_GS_BRV
DELETE FROM PEN.T_BPEN075_ARBTAB_2
DELETE FROM PEN.T_BPEN021_ARBTAB
DELETE FROM PEN.T_BPEN035_ARBTAB
DELETE FROM PEN.T_BPEN031_OPPTJN
DELETE FROM PEN.T_BPEN075_LOPENDE_VEDTAK
DELETE FROM PEN.T_BPEN020_ARBTAB
DELETE FROM PEN.T_LIGNET_INNTEKT
DELETE FROM PEN.T_BPEN005_GS_YT2
DELETE FROM PEN.T_BPEN005_GS_YT1
DELETE FROM PEN.T_BPEN058_ARB_TAB
DELETE FROM PEN.T_AFP_ETTEROPP
DELETE FROM PEN.T_BPEN068_FEILMELDING
DELETE FROM PEN.T_AFP_ETTER_SPK a
DELETE FROM PEN.T_IVERKS_KONV i
DELETE FROM PEN.T_IVERKS_KONV i
DELETE FROM PEN.T_OS_OPPDRLINJE_S
DELETE FROM PEN.T_BPEN039_ARBTAB
DELETE FROM PEN.T_GOMR_PATCH_ARB_T
DELETE FROM PEN.T_BATCH_PERSON_FILTER
DELETE FROM PEN.T_BPEN058_PERSONID
DELETE FROM PEN.T_INNTEKT_TPEN750
DELETE FROM PEN.T_BPEN093_OPPGAVE
DELETE FROM PEN.T_BPEN093_VEDTAK
DELETE FROM PEN.T_BPEN093_ARB_TAB
DELETE FROM PEN.T_BPEN093_INPUT
DELETE FROM PEN.T_BPEN093_SAK
DELETE FROM PEN.T_BPEN096_ARB_TAB
DELETE FROM PEN.T_VURDERT_SIVILST
DELETE FROM PEN.T_VURDERT_SIVILST
DELETE FROM PEN.T_SKJEMA_BARN
DELETE FROM PEN.T_SKJEMA_RELASJON
DELETE FROM PEN.T_BREVBESTILLING
DELETE FROM PEN.T_VILKAR
DELETE FROM PEN.T_OMSORG_GRUNNLAG
DELETE FROM PEN.T_OMSORG_GRUNNLAG
DELETE FROM PEN.T_I_GODSKRIV
delete from PEN.T_I_SAERF_PERSON
DELETE FROM PEN.T_BPEN056_GS_TAB
DELETE FROM PEN.T_BPEN056_GS_TAB
DELETE FROM PEN.T_PERS_TIL_AVST
DELETE FROM PEN.T_PERS_TIL_GOMR
DELETE FROM PEN.T_LEVEATTEST_HIST
DELETE FROM PEN.T_PENSJONSORDNING
DELETE FROM PEN.T_BPEN055_ARB_TAB
DELETE FROM PEN.T_BPEN055_ARB_TAB
DELETE FROM PEN.T_FORST_VIRK_DATO
DELETE FROM PEN.T_FORST_VIRK_DATO
DELETE FROM PEN.T_I_DIST_LA
DELETE FROM PEN.T_GODSKRIVES
DELETE FROM PEN.T_GODSKRIVES
DELETE FROM PEN.T_INNTEKTSKONTROLL
DELETE FROM PEN.T_SKJEMA
DELETE FROM PEN.T_KRAV_ARSAK
DELETE FROM PEN.T_I_INNT_KONT_BR
DELETE FROM PEN.T_AFP_ETTER_FOLGE
DELETE FROM PEN.T_I_SAERF_VEDTAK
DELETE FROM PEN.T_SAK_AUTOBEH
DELETE FROM PEN.T_BPEN018_ARB_TAB
DELETE FROM PEN.T_BPEN013_ARB_TAB
DELETE FROM PEN.T_BPEN015_OPPTJENINGSAR
DELETE FROM PEN.T_BPEN015_ARB_TAB
DELETE FROM PEN.T_BPEN056_ARBTAB
DELETE FROM PEN.T_FNR_ENDRING_HIST
DELETE FROM PEN.T_SOSKEN_DET
DELETE FROM PEN.T_BARN_DET
DELETE FROM PEN.T_PERSON_DET
DELETE FROM PEN.T_BEREGNING_VILKAR
DELETE FROM PEN.T_TELEFON
DELETE FROM PEN.T_SKJEMA_PERS_OPPL
DELETE FROM PEN.T_JOURNALPOST_UTL
DELETE FROM PEN.T_BPEN029_SAK_ARBTAB
DELETE FROM PEN.T_SAK_TILGANG
delete from PEN.T_AFP_OFF_GRNL
delete from PEN.T_AFP_OFF_GRNL
delete from PEN.T_AFP_OFF_GRNL
DELETE FROM PEN.T_AFPEO_UTB_PER
DELETE FROM PEN.T_UTTAKSGRAD
DELETE FROM PEN.T_BPEN029_OPPG_ARBTAB
DELETE FROM PEN.T_I_OPPGAVE
DELETE FROM PEN.T_HENDELSE
DELETE FROM PEN.T_SIMULERT_UTB_PR
DELETE FROM PEN.T_BPEN068_ARB_TAB
DELETE FROM PEN.T_KONTROLLPUNKT
DELETE FROM PEN.T_BPEN052_PERSON
DELETE FROM PEN.T_BPEN052_PERSON
DELETE FROM PEN.T_BPEN052_SAK
DELETE FROM PEN.T_BPEN052_ARB_PERS
DELETE FROM PEN.T_BPEN052_ARB_PERS
DELETE FROM PEN.T_BPEN052_ARB_VEDT
DELETE FROM PEN.T_BPEN052_ARB_SAK
DELETE FROM PEN.T_UFORE_PERIODE
DELETE FROM PEN.T_BPEN029_ARB_TAB
DELETE FROM PEN.T_OS_KVITTERING
DELETE FROM PEN.T_AFPEO
DELETE FROM PEN.T_BPEN077_SAMHANDLER
DELETE FROM PEN.T_BPEN025_HISTORY
DELETE FROM PEN.T_AUTOBREV
DELETE FROM PEN.T_AUTOBREV
DELETE FROM PEN.T_VEDTAK_BERP_REL
DELETE FROM PEN.T_VEDOMR_KRAV_MAP
DELETE FROM PEN.T_VEDTAK_TIL_OMR
DELETE FROM PEN.T_TILBAKEK_PR_MND
DELETE FROM PEN.T_TILBAKEK_PR_AR
DELETE FROM PEN.T_TILBAKEK_TOTAL
DELETE FROM PEN.T_TAP_BER_METODE
DELETE FROM PEN.T_BEHOLDNING
DELETE FROM PEN.T_BELOPSENDRING
DELETE FROM PEN.T_PERIODE_ARSAK
DELETE FROM PEN.T_INFO_PAVIRK_REL
DELETE FROM PEN.T_KRAV_ENHET_HIST
DELETE FROM PEN.T_KRAV_RETUR_ARSAK
DELETE FROM PEN.T_VILKAR_UP
DELETE FROM PEN.T_VILK_VURD_UP
DELETE FROM PEN.T_UTENLAND_OPPH
DELETE FROM PEN.T_SKJEMA_AFP_PRIV
DELETE FROM PEN.T_VENTETILLEG_GRNL
DELETE FROM PEN.T_BEREGNING_REL
DELETE FROM PEN.T_BEREGNING_REL
DELETE FROM PEN.T_BEREGNING_REL
DELETE FROM PEN.T_UTBETALINGSGRAD_UT
DELETE FROM PEN.T_UFORE_OPPTJENING_GRUNNLAG
DELETE FROM PEN.T_OMSRG_OVRF_GRNL
DELETE FROM PEN.T_DAGP_GRUNNLAG
DELETE FROM PEN.T_INNG_EKSP_GRNL
DELETE FROM PEN.T_YRKESSKADE
DELETE FROM PEN.T_INST_OP_FU_PE
DELETE FROM PEN.T_ARBEIDSFORHOLDGRUNNLAG_IEU
DELETE FROM PEN.T_TRYGDETID_GRNL
DELETE FROM PEN.T_TRYGDETID_GRNL
DELETE FROM PEN.T_BARNEKULL
DELETE FROM PEN.T_TJENESTEPEN_GRNL
DELETE FROM PEN.T_VERNEPLIKT_AR
DELETE FROM PEN.T_AFPEO_GRUNNLAG
DELETE FROM PEN.T_GJELDENDE_VEDTAK_EO_AR
DELETE FROM PEN.T_BPEN092_ARB_TAB
DELETE FROM PEN.T_UTBETALINGSGRAD_UT
DELETE FROM PEN.T_UFORE_OPPTJENING_GRUNNLAG
DELETE FROM PEN.T_EO_UT_HISTORIK
DELETE FROM PEN.T_INNTEKT
DELETE FROM PEN.T_INNTEKT
DELETE FROM PEN.T_INNTEKT
DELETE FROM PEN.T_ETTEROPPGJOR_DET
DELETE FROM PEN.T_UT_ETTEROPPGJOR
DELETE FROM PEN.T_INST_OPPH_REF
DELETE FROM PEN.T_TRYGDEAVTALE
DELETE FROM PEN.T_OMSRG_GODS_GRNL
DELETE FROM PEN.T_KLAGE_ANKE_GRNL
DELETE FROM PEN.T_KLAGE_ANKE_GRNL
DELETE FROM PEN.T_OPPTJN_TYPE_MAP
DELETE FROM PEN.T_OPPTJN
DELETE FROM PEN.T_POENGAR_MANUELL
DELETE FROM PEN.T_TRYGDEAVTAL_DET
DELETE FROM PEN.T_FORSTEG_TJ_PER
DELETE FROM PEN.T_FORSTEGANG_TJ
DELETE FROM PEN.T_TRYGDETID_KONV
DELETE FROM PEN.T_TRYGDETID_KONV
DELETE FROM PEN.T_TT_UTL_TRGD_AVT
DELETE FROM PEN.T_TT_UTL_TRGD_AVT
DELETE FROM PEN.T_TRYGDETID_EOS
DELETE FROM PEN.T_TRYGDETID_EOS
DELETE FROM PEN.T_BEREGNET_UTB_PERIODE_UT
DELETE FROM PEN.T_BPEN025_ARB_PERS
DELETE FROM PEN.T_BPEN025_AVSTEMMING_DETALJ
DELETE FROM PEN.T_OS_TRANSAKSJON
DELETE FROM PEN.T_BPEN090_ARB_TAB
DELETE FROM PEN.T_BPEN091_BRUKER
DELETE FROM PEN.T_BPEN091_INNTEKT
DELETE FROM PEN.T_UTEO_REKJORING
delete from PEN.T_BPEN077_ARB_TAB
delete from PEN.T_FT_DT_ARSAK
delete from PEN.T_BT_VILKAR
delete from PEN.T_BT_VURDERING_PERIODE
delete from PEN.T_ENDRET_OPPTJENINGSAR
delete from PEN.T_FRITEKST_VURDERING
delete from PEN.T_VILKARS_VEDTAK_BEGR
delete from PEN.T_VILKARS_VEDTAK_BEGR
DELETE FROM PEN.T_LAAST_DATA_LOGG_ELEMENT
delete from PEN.T_LAAST_DATA_LOGG
DELETE FROM PEN.T_INNTEKT_ABONNEMENT inntekt_abonnement
DELETE FROM PEN.T_INNTEKT_ABONNEMENT inntekt_abonnement
delete from PEN.T_AFP_TPO_UP_GRUNNLAG
DELETE FROM PEN.T_AFP_TPO_UP_GRUNNLAG
delete from PEN.T_BREV_INFO
delete from PEN.T_BPEN002_MELDING
delete from PEN.T_BPEN002_BERORT_SAK
delete from PEN.T_BPEN002_INFOBREV
delete from PEN.T_BPEN002_OPPGAVE
delete from PEN.T_BPEN002_YTELSE
UPDATE PEN.T_BEREGNING_RES br SET br.BER_PERIODE_ID = NULL, br.BER_PER_REVURD_ID = NULL
UPDATE PEN.T_VEDTAK v SET v.BER_PERIODE_ID = NULL
DELETE FROM PEN.T_BER_PERIODE
DELETE FROM PEN.T_BER_PERIODE
DELETE FROM PEN.T_BER_PERIODE
DELETE FROM PEN.T_BER_PERIODE
UPDATE PEN.T_VILKARSPROV_INFO vi SET vi.VILK_PROV_INFO_2011 = NULL, vi.VILK_PROV_INFO_2025   = NULL
DELETE FROM PEN.T_VILKARSPROV_INFO
DELETE FROM PEN.T_VILKARSPROV_INFO
UPDATE PEN.T_SISTE_UFORE_BER su SET su.UFORE_EXTRA_ID = NULL
DELETE FROM PEN.T_UFORE_EXTRA
UPDATE PEN.T_BEREGNING b SET b.TRYGDETID_ID = NULL
DELETE FROM PEN.T_TRYGDETID
DELETE FROM PEN.T_TRYGDETID
DELETE FROM PEN.T_ANT_AR_MND_DAG
UPDATE PEN.T_BEREGNING b SET b.simulering_res_id = NULL
DELETE FROM PEN.T_SIMULERING_RES
UPDATE PEN.T_INST_OP_RE_PE inst SET inst.REF_INST_OP_RE_PE = NULL
DELETE FROM PEN.T_INST_OP_RE_PE
DELETE FROM PEN.T_INST_OP_RE_PE
UPDATE PEN.T_KRAVLINJE kl SET kl.KRAVLINJE_S_ID = NULL
DELETE FROM PEN.T_KRAVLINJE_S
UPDATE PEN.T_VILKAR_VEDTAK vv SET vv.kravlinje_id = NULL
DELETE FROM PEN.T_KRAVLINJE
DELETE FROM PEN.T_KRAVLINJE
UPDATE PEN.T_PERSON_GRUNNLAG pg SET pg.gen_historik_id = NULL
DELETE FROM PEN.T_GEN_HISTORIK
UPDATE PEN.T_YTELSE_KOMP yt SET yt.bereg_nokkel_id = NULL
DELETE FROM PEN.T_BEREG_NOKKEL
DELETE FROM PEN.T_BEREG_NOKKEL
UPDATE PEN.T_VILKAR_VEDTAK vv SET vv.BEHANDL_PERIODE_ID = NULL
DELETE FROM PEN.T_BEHANDL_PERIODE
DELETE FROM PEN.T_BEHANDL_PERIODE
UPDATE PEN.T_YTELSE_KOMP yt SET yt.beregning_id = NULL, yt.FRADRAG_YK_BEREGNING = NULL
DELETE FROM PEN.T_BEREGNING
UPDATE PEN.T_KRAVHODE k SET k.SIST_AP_BER_2011_ID = NULL
DELETE FROM PEN.T_SIST_AP_BER_2011
UPDATE PEN.T_BEREGNING_RES br SET br.UFORETRYGD_BEREGNING_ID = NULL, br.BEREGNING_AFP_PRIVAT_FK   = NULL
DELETE FROM PEN.T_BEREGNING_2011
UPDATE PEN.T_KONVERTERINGSGRUNNLAG_UT k SET k.ufore_grnl_id = NULL
DELETE FROM PEN.T_UFORE_GRNL
DELETE FROM PEN.T_BPEN091_INNTEKT
UPDATE PEN.T_PERSON_GRUNNLAG pg SET pg.OVERGANGSINFO_UP_TIL_UT_ID = NULL
DELETE FROM PEN.T_OVERGANGSINFO_UP_TIL_UT
DELETE FROM PEN.T_GRUNNLAG_VEDLEGG
DELETE FROM PEN.T_PERSON_GRUNNLAG
DELETE FROM PEN.T_BASISPENSJON
DELETE FROM PEN.T_VILKAR_VEDTAK
DELETE FROM PEN.T_AFP_HISTORIK
DELETE FROM PEN.T_SIMULERING
UPDATE PEN.T_BEREGNING_RES br SET br.BER_RES_AP_2011_2016_ID = NULL, br.BER_RES_AP_2025_2016_ID   = NULL
DELETE FROM PEN.T_BEREGNING_RES
UPDATE PEN.T_KRAVHODE k SET k.KONVERTERINGSGRUNNLAG_UT_ID = NULL
DELETE FROM PEN.T_KONVERTERINGSGRUNNLAG_UT
UPDATE PEN.T_KRAVHODE k SET k.siste_ufore_ber_id = NULL
DELETE FROM PEN.T_SISTE_UFORE_BER
DELETE FROM PEN.T_KONVERTERINGSGRUNNLAG
DELETE FROM PEN.T_YTELSE_KOMP
DELETE FROM PEN.T_BEREGNING_INFO
UPDATE PEN.T_EO_UT_HISTORIK euh set euh.FORRIGE_EO_UT_HISTORIK_ID = NULL
delete from PEN.T_EO_UT_HISTORIK
update PEN.T_KRAVHODE set FORRIGE_VEDTAK_TID = null
update PEN.T_VEDTAK set REL_ALDER_VEDTAK = null
update PEN.T_VEDTAK set REL_AFP_PR_VEDTAK = null
update PEN.T_VEDTAK set BASERT_PA_VEDTAK = null
delete from PEN.T_VEDTAK
delete from PEN.T_UFORE_HISTORIK
update PEN.T_KRAVHODE set KRAVHODE_ID_FOR = null
update PEN.T_KRAVHODE set FORRIGE_IVERKSATTE_KRAV = null
delete from PEN.T_KRAVHODE
delete from PEN.T_SAK
delete from PEN.T_PERSON
delete from PEN.T_POENGREKKE
delete from PEN.T_SLUTTPOENGTALL
delete from PEN.T_PEN_UNDER_UTBET
delete from PEN.T_ANVENDT_TRYGDETID
delete from PEN.T_FREMSKRIVING_DET
delete from PEN.T_LONNSVEKST_DET
delete from PEN.T_JUST_GAR_PEN_NIV
delete from PEN.T_F_MIN_PEN_NIVA
delete from PEN.T_JUSTERING_INFO
delete from PEN.T_MIN_PEN_NIVA
delete from PEN.T_VILKVEDTAK_UFORETRYGD_GRNL
delete from PEN.T_BEREGNET_UTBINFOGRUNN_UT
delete from PEN.T_OPPTJENING_UT
delete from PEN.T_EGENOPPTJN_UT
delete from PEN.T_GJT_INFORMASJON
delete from PEN.T_OVERGANGSBELOP
delete from PEN.T_JUSTERT_BELOP
delete from PEN.T_AVKORT_INFO
delete from PEN.T_SKATTEKOMP_BELOP
delete from PEN.T_BEREGNINGSGRUNNLAG
delete from PEN.T_MINSTEYTELSE
delete from PEN.T_SATS_MINSTEYTELSE
delete from PEN.T_BER_UFORE_PER
delete from PEN.T_UFORE_EXTRA_UT
delete from PEN.T_LONNSVEKST_INFO
delete from PEN.T_REGULERING_INFO
