apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-testdata-server
  namespace: default
  labels:
    team: teampensjon
spec:
  image: navikt/pensjon-testdata-server:dev
ingresses:
  - "https://pensjon-testdata-server.nais.adeo.no/"
  liveness:
    path: isAlive
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  prometheus:
    enabled: true