apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-testdata-server
  namespace: t4
  labels:
    team: pensjontestdata
spec:
  image: {{ image }}
  ingresses:
    - https://pensjon-testdata-server-t4.nais.preprod.local
  liveness:
    path: api/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  replicas:
    min: 2
    max: 2
  readiness:
    path: api/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  prometheus:
    enabled: true
    path: api/prometheus
  env:
    - name: "SECRET_BASEDIR"
      value: "/"
    - name: "pen_db_enabled"
      value: "true"
    - name: "popp_db_enabled"
      value: "true"
    - name: "sam_db_enabled"
      value: "true"
    - name: "moog_db_enabled"
      value: "false"
    - name: "sts_endpoint_url"
      value: "https://security-token-service-t4.nais.preprod.local"
    - name: "popp_endpoint_url"
      value: "https://pensjon-popp-t4.nais.preprod.local/popp/api"
    - name: "pen_vedtaksbrev_endpoint"
      value: "https://pensjon-pen-t4.dev.adeo.no/pen/services/Vedtaksbrev"
    - name: "pen_auto_omregning_endpoint"
      value: "https://wasapp-t4.adeo.no/pensjon-ws/BehandleAutomatiskOmregning_v1"
    - name: "norg_endpoint_url"
      value: "https://app-t1.adeo.no/norg2/api"
    - name: "preg_rest_veiet_grunnbelop_endpoint_url"
      value: "https://pensjon-preg-t4.nais.preprod.local/grunnbelop/veiet"
    - name: "db_startup_wait_seconds"
      value: "300"
    - name: "brevmetadata_endpoint_url"
      value: "https://pensjon-brevmetadata-pensjonsbrev.dev.adeo.no/api/brevdata"
  vault:
    enabled: true
    paths:
      - kvPath: "oracle/data/dev/config/pen_t4"
        mountPath: "/secrets/db/pen"
      - kvPath: "oracle/data/dev/config/popp_t4"
        mountPath: "/secrets/db/popp"
      - kvPath: "oracle/data/dev/config/sam_t4"
        mountPath: "/secrets/db/sam"
      - kvPath: "oracle/data/dev/creds/pen_t4-pen_testdata"
        mountPath: "/secrets/oracle/pen"
      - kvPath: "oracle/data/dev/creds/popp_t4-popp_testdata"
        mountPath: "/secrets/oracle/popp"
      - kvPath: "oracle/data/dev/creds/sam_t4-sam_testdata"
        mountPath: "/secrets/oracle/sam"
      - kvPath: "serviceuser/data/test/srvpensjon"
        mountPath: "/secrets/srvpensjon"
      - kvPath: "kv/preprod/fss/pensjon-testdata-server/default"
        mountPath: "/secrets/app"