apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-testdata-dolly-facade
  namespace: default
  labels:
    team: teampensjon
spec:
  image: repo.adeo.no:5443/navikt/pensjon-testdata-dolly-facade:IMAGE_VERSION
  port: 8081
  ingresses:
    - https://pensjon-testdata-dolly-facade.nais.preprod.local
  liveness:
    path: isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: prometheus