name: Build and deploy facade on push to master

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-facade.yml'
      - 'facade/**'

env:
  TARGET: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-facade
  IMAGE: ${TARGET}:${{ github.sha }}

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**facade/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd facade
          ./mvnw package -DskipTests
          docker build -t ${IMAGE} -t ${TARGET}:latest .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy facade to NAIS
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: facade/nais.yaml
