name: Build and deploy server

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-server.yml'
      - 'server/**'
      - 'client/**'
    branches: [master]

env:
  LATEST: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-server:latest
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-server:${{ github.sha }}

jobs:
  tag_build_and_deploy:
    name: 'Server - build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**server/pom.xml') }}
          restore-keys: |
            maven-${{ hashFiles('**server/pom.xml') }}
            maven-
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn package -B
          cd server
          docker build --tag ${IMAGE} .
          docker tag ${IMAGE} ${LATEST}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker push ${LATEST}

  deploy_q2:
    name: Deploy server to NAIS - Q2 namespace
    needs: tag_build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q2.yaml

  deploy_t4:
    name: Deploy server to NAIS - T4 namespace
    needs: tag_build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-t4.yaml

  deploy_q4:
    name: Deploy server to NAIS - Q4 namespace
    needs: tag_build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q4.yaml

  deploy_q1:
    name: Deploy server to NAIS - Q1 namespace
    needs: tag_build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q1.yaml