name: Build and deploy client

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-client.yml'
      - 'client/**'
    branches: [master]

env:
  LATEST: ghcr.io/${{ github.repository }}/pensjon-testdata-client:latest
  IMAGE: ghcr.io/${{ github.repository }}/pensjon-testdata-client

jobs:
  build_and_publish_image:
    name: 'Client - build docker image'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build and publish Docker image
        run: |
          cd client
          npm install
          npm run build
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$IMAGE:$TIME-$COMMIT"
          docker build -t ${VERSION} -t ${LATEST} .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${VERSION}
          docker push ${LATEST}
  deploy_q2:
    name: Deploy client to NAIS - Q2 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q2.yaml

  deploy_t4:
    name: Deploy client to NAIS - T4 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-t4.yaml

  deploy_q4:
    name: Deploy client to NAIS - Q4 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q4.yaml

  deploy_q1:
    name: Deploy client to NAIS - Q1 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q1.yaml