name: Build and deploy dolly-facade on push to master

on:
  push:
    paths:
      - 'dolly-facade/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-server:${{ github.sha }}

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**dolly-facade/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dolly-facade
          chmod +x mvnw
          ./mvnw package -DskipTests
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy dolly-facade to NAIS
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: dolly-facade/nais.yaml