name: Build and deploy facade

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-facade.yml'
      - 'facade/**'
    branches: [master]

env:
  LATEST: ghcr.io/${{ github.repository }}/pensjon-testdata-facade:latest
  IMAGE: ghcr.io/${{ github.repository }}/pensjon-testdata-facade:${{ github.sha }}

jobs:
  build_and_publish_image:
    name: 'Facade - build docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**facade/pom.xml') }}
          restore-keys: |
            maven-${{ hashFiles('**facade/pom.xml') }}
            maven-
      - name: Build and publish Docker image
        run: |
          cd facade
          mvn package -B
          docker build --tag ${IMAGE} .
          docker tag ${IMAGE} ${LATEST}
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${IMAGE}
          docker push ${LATEST}
  deploy:
    name: Deploy facade to NAIS
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: facade/nais.yaml
