name: Build and deploy server

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-server.yml'
      - 'server/**'
      - 'client/**'
    branches: [master]

env:
  LATEST: ghcr.io/${{ github.repository }}/pensjon-testdata-server:latest
  IMAGE: ghcr.io/${{ github.repository }}/pensjon-testdata-server

jobs:
  build_and_publish_image:
    name: 'Server - build docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**server/pom.xml') }}
          restore-keys: |
            maven-${{ hashFiles('**server/pom.xml') }}
            maven-
      - name: Build and publish Docker image
        run: |
          mvn package -B
          cd server
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$IMAGE:$TIME-$COMMIT"
          docker build -t ${VERSION} -t ${LATEST} .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${LATEST}
          docker push ${VERSION}

  deploy_q2:
    name: Deploy server to NAIS - Q2 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q2.yaml

  deploy_t4:
    name: Deploy server to NAIS - T4 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-t4.yaml

  deploy_q4:
    name: Deploy server to NAIS - Q4 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q4.yaml

  deploy_q1:
    name: Deploy server to NAIS - Q1 namespace
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: server/nais-q1.yaml