name: Build and deploy client

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy-client.yml'
      - 'client/**'

env:
  LATEST: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-client:latest
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pensjon-testdata-client:${{ github.sha }}

jobs:
  build:
    name: 'Build client'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**client/package-lock.json') }}
          restore-keys: |
            node-${{ hashFiles('**client/package-lock.json') }}
            node-
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd client
          npm install
          npm run build

  tag_build_and_deploy:
    name: 'Client  - build and deploy'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd client
          npm install
          npm run build
          docker build --tag ${IMAGE} .
          docker tag ${IMAGE} ${LATEST}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker push ${LATEST}
  deploy_q2:
    name: Deploy client to NAIS - Q2 namespace
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q2.yaml

  deploy_t4:
    name: Deploy client to NAIS - T4 namespace
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-t4.yaml

  deploy_q4:
    name: Deploy client to NAIS - Q4 namespace
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q4.yaml

  deploy_q1:
    name: Deploy client to NAIS - Q1 namespace
    needs: tag_build_and_deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: client/nais-q1.yaml