name: server Docker Image CI

env:
  VERSION: $(date +%s)

on:
  push:
    branches: [ cd-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: server:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build pensjon-testdata-server image
        uses: actions/checkout@v2
        run: |
          cd server
          docker build . --file Dockerfile --tag "$IMAGE_NAME"
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push "$IMAGE_NAME"