name: Redeploy facade

on: [workflow_dispatch]

env:
  IMAGE: ghcr.io/${{ github.repository }}/pensjon-testdata-facade:latest

jobs:
  deploy:
    name: Deploy facade to NAIS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: facade/nais.yaml
